# TypeProf 0.21.3

# Classes
module Elisp2any
  VERSION: String

  class CodeBlock
    extend Forwardable
    @node: Node

    def initialize: (Node node) -> void
    def append: (untyped source, untyped end_byte) -> untyped
  end

  class InlineCode
    attr_reader content: untyped
    def initialize: (untyped content) -> void
  end

  class Line
    extend Forwardable
    include Enumerable
    @chunks: Array[(InlineCode | String)?]

    def initialize: (Array[(InlineCode | String)?] chunks) -> void
    def self.parse: (String string) -> Line
  end

  class Heading
    extend Forwardable
    @node: Node

    attr_reader level: Integer
    attr_reader content: String
    def initialize: (Node node, Integer level, String content) -> void
    def name_and_synopsis: -> [untyped, untyped]?
    def commentary?: -> bool
    def code?: -> bool
    def final_name: -> String?
  end

  class Paragraph
    extend Forwardable
    include Enumerable
    @node: Node
    @lines: [Line]

    attr_reader end_row: untyped
    def initialize: (Node node, [Line] lines, untyped end_row) -> void
    def code?: -> false
  end

  class Node
    attr_reader range: Range
    attr_reader content: untyped
    def append: (untyped source, untyped end_byte) -> untyped
    def initialize: (untyped content, Range range) -> void
  end

  class File
    attr_reader name: nil
    attr_reader synopsis: nil
    attr_reader commentary: Array[(CodeBlock | Heading | Paragraph)?]
    attr_reader code: Array[CodeBlock | Heading | Paragraph]
    def self.parse: (untyped source) -> File
    def initialize: (name: nil, synopsis: nil, commentary: Array[(CodeBlock | Heading | Paragraph)?], code: Array[CodeBlock | Heading | Paragraph]) -> void
  end

  class HTMLRenderer
    extend Forwardable
    @file: untyped

    def initialize: (untyped file) -> void
    def render: -> String

    private
    def render_paragraph: (untyped paragraph) -> String
    def render_block: (untyped block, level: untyped) -> String
    def erb_render: (String path) -> String
    def h: (untyped string) -> String
  end

  class Error < StandardError
  end
end
