#!/usr/bin/env ruby

require 'optparse'

$LOAD_PATH << File.join(__dir__, "../lib")
require 'elisp'

input = $stdin
output = $stdout
css = nil

OptionParser.new do |parser|
  parser.on('--input=PATH') do |path|
    input = File.open(path)
  end

  parser.on('--output=PATH') do |path|
    output = File.open(path, 'w')
  end

  parser.on('--css=PATH') do |path|
    css = path
  end
end.parse!

Elisp.parse(input).write(output, css:)
