#!/usr/bin/env ruby

require_relative '../lib/elisp2any'
require_relative '../lib/elisp2any/html_renderer'
require 'optparse'

input = $stdin
output = $stdout
css = nil

OptionParser.new do |parser|
  parser.on('--input=PATH') do |path|
    input = File.open(path)
  end

  parser.on('--output=PATH') do |path|
    output = File.open(path, 'w')
  end

  parser.on('--css=PATH') do |path|
    css = path
  end
end.parse!

file = Elisp2any::File.parse(input)
renderer = Elisp2any::HTMLRenderer.new(file, css:)
output.write(renderer.render)
